
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.network "forwarded_port", guest: 80, host: 8082, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.1.102", netmask: "255.255.255.0"
  config.vm.provision "shell", path: "provision.sh"
end
